---
#####################
# Deploy to Staging #
#####################

kind: pipeline
type: exec
name: deploy-staging

trigger:
  event:
  - push

steps:
- name: deploy
  commands:
  - pip install -r requirements.txt
  - python webapp/app.py

node:
  group: wordle