---
#####################
# Deploy to Staging #
#####################

kind: pipeline
type: exec
name: deploy-staging

trigger:
  event:
  - push

steps:
- name: deploy
  commands:
  - python -m venv .venv
  - source .venv/bin/activate
  - pip install -r requirements.txt
  - python webapp/app.py

node:
  group: wordle