---
#####################
# Deploy to Staging #
#####################

kind: pipeline
type: exec
name: deploy-staging

trigger:
  event:
  - push

steps:
- name: deploy
  commands:
  - pip3 install -r requirements.txt
  - gunicorn --bind 0.0.0.0:5000 --chdir webapp app:app 
  environment:
    GOOGLE_CLIENT_ID:
      from_secret: wordle_google_client_id_stg
    GOOGLE_CLIENT_SECRET:
      from_secret: wordle_google_client_secret_stg
    ALLOWED_DOMAINS:
      from_secret: allowed_domains
node:
  group: wordle

---
########################
# Deploy to Production #
########################

kind: pipeline
type: exec
name: deploy-production

trigger:
  event: 
  - promote
  target:
  - production

steps:
# Deploy Bot on Python 3.12
- name: deploy
  commands:
    - pip3 install -r requirements.txt
    - gunicorn --daemon --bind 0.0.0.0:8000 --chdir webapp app:app 
  environment:
    GOOGLE_CLIENT_ID:
      from_secret: wordle_google_client_id_prod
    GOOGLE_CLIENT_SECRET:
      from_secret: wordle_google_client_secret_prod
    WSGI_X_FOR: 1
    WSGI_X_PROTO: 1
    WSGI_X_HOST: 1
    WSGI_X_PREFIX: 1
    ALLOWED_DOMAINS: gmail.com
